language: python
python:
    - "2.6"
    - "2.7"
services:
    - mongodb
    - rabbitmq
install:
    - pip install --allow-all-external -r requirements.txt
    - pip install coveralls
script:
    coverage run ./runtest.py
after_success:
    - coverage combine
    - coveralls
